import { MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import React from 'react';

import '../../node_modules/normalize.css/normalize.css';
import '../shared/styles/main.scss';
import { Footer } from './layout/footer/footer';
import { Header } from './layout/header/header';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <MantineProvider>
          <Header />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
